### ISSUE TITLE
Binder Error

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-workshop#21]
Right now when we click on a binder icon the following error happens:

```scala
ValueError: The extension "@almond-sh/scalafmt" does not yet support the current version of JupyterLab.
```

**Comment by pomadchin** [comment]
As workaround for now we can use this URI: https://notebooks.gesis.org/binder/v2/gh/geotrellis/geotrellis-workshop/d71a716853dc54532502da7d58fabe57e9802397

**Comment by stjimreal** [comment]
```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.4 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.4 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
See the log file for details:  /tmp/jupyterlab-debug-7jpozmj8.log
Removing intermediate container b946b21e3b95
```

Conflicting Dependencies in [mybinder.com](https://mybinder.org/)

**Comment by pomadchin** [comment]
Fixed in terms of https://github.com/geotrellis/geotrellis-workshop/pull/22
